---

- name: update cache
  apt:
    update_cache: true
- name: install openjdk-11
  apt:
    name: openjdk-11-jdk
    state: latest
- name: install curl
  apt:
    name: curl
    state: latest
- name: install wget
  apt:
    name: wget
    state: latest
- name: install zip
  apt:
    name: zip
    state: latest
- name: install unzip
  apt:
    name: unzip
    state: latest